config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :developers

  namespace :api do
    namespace :v1 do
      resources :developers, only: [:show]
    end
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
# frozen_string_literal: true

class Developer < ApplicationRecord
  has_many :developer_languages, dependent: :destroy
  has_many :languages, through: :developer_languages

  has_many :developer_programming_languages, dependent: :destroy
  has_many :programming_languages, through: :developer_programming_languages

  validates :email, presence: true, uniqueness: true
end

app/models/developer_language.rb
# frozen_string_literal: true

class DeveloperLanguage < ApplicationRecord
  belongs_to :developer, inverse_of: :developer_languages
  belongs_to :language, inverse_of: :developer_languages
end

app/models/developer_programming_language.rb
# frozen_string_literal: true

class DeveloperProgrammingLanguage < ApplicationRecord
  belongs_to :developer, inverse_of: :developer_programming_languages
  belongs_to :programming_language, inverse_of: :developer_programming_languages
end

app/models/language.rb
# frozen_string_literal: true

class Language < ApplicationRecord
  has_many :developer_languages, dependent: :destroy
  has_many :developers, through: :developer_languages

  validates :code, presence: true, uniqueness: true
end

app/models/programming_language.rb
# frozen_string_literal: true

class ProgrammingLanguage < ApplicationRecord
  has_many :developer_programming_languages, dependent: :destroy
  has_many :developers, through: :developer_programming_languages

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::API
    rescue_from Exception, with: :error_500
    rescue_from ActiveRecord::RecordNotFound, with: :error_404

    def error_500(e)
      logger.error("#{e.message}\n#{params.to_unsafe_h}\n#{e.backtrace.join("\n")}")
      render json: {}, status: :internal_server_error
    end

    def error_404
      render json: {}, status: :not_found
    end
  end
end

app/controllers/api/v1/developers_controller.rb
module Api
  module V1
    class DevelopersController < Api::BaseController
      before_action :set_developer, only: %i[show]

      def show
        if stale?(last_modified: @developer.updated_at.utc)
          cache_options = { compress: true, expires_in: 24.hours, race_condition_ttl: 10 }
          Rails.cache.fetch("#{@developer.cache_key}/#{__method__}", cache_options) do
            render json: @developer, key_transform: :underscore
          end
        end
      end

      def set_developer
        @developer = Developer.find(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
# frozen_string_literal: true

class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[show edit update destroy]

  # GET /developers
  def index
    @developers = Developer.all
  end

  # GET /developers/1
  def show; end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit; end

  # POST /developers
  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      redirect_to @developer, notice: 'Developer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /developers/1
  def update
    if @developer.update(developer_params)
      redirect_to @developer, notice: 'Developer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /developers/1
  def destroy
    @developer.destroy
    redirect_to developers_url, notice: 'Developer was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_developer
    @developer = Developer.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def developer_params
    params.require(:developer).permit(:email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/developers_helper.rb
# frozen_string_literal: true

module DevelopersHelper
end

app/views/developers/_form.html.slim
= form_for @developer do |f|
  - if @developer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@developer.errors.count, "error")} prohibited this developer from being saved:"
      ul
        - @developer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
    = f.label :programming_language
    = f.select :programming_languages
  .actions = f.submit

app/views/developers/edit.html.slim
h1 Editing developer

== render 'form'

=> link_to 'Show', @developer
'|
=< link_to 'Back', developers_path

app/views/developers/index.html.slim
h1 Listing developers

= form_for @developers_search_form, url: developers_path, method: :get do |f|
  = f.select :programming_language_id, ProgrammingLanguage.pluck(:name, :id), { prompt: 'select programing language' }
  = f.select :language_id, Language.pluck(:code, :id), { prompt: 'select language' }
  = f.submit 'Search'

table
  thead
    tr
      th Email
      th programming_languages
      th languages

  tbody
    - @developers.each do |developer|
      tr
        td = developer.email
        td
          = developer.programming_languages.pluck(:name).join(', ')
        td
          = developer.languages.pluck(:code).join(', ')

= link_to 'New Developer', new_developer_path

app/views/developers/new.html.slim
h1 New developer

== render 'form'

= link_to 'Back', developers_path

app/views/developers/show.html.slim
p#notice = notice

p
  strong Email:
  = @developer.email

=> link_to 'Edit', edit_developer_path(@developer)
'|
=< link_to 'Back', developers_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsTraining
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag    'application'
  body
    = yield